[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "eo-basic-example"
version = "0.0.1-dev"
description = "Quick examples working with satellite data."
readme = "README.md"
requires-python = ">=3.12,<4.0"
license = "MIT"
authors = [{ name = "Jordan Pinder", email = "jordan.pinder.dev@gmail.com" }]
classifiers = [
    "Environment :: Web Environment",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = [
    "requests>=2.32.2,<3.0.0",
    "ipykernel>=6.20.2,<7.0.0",
    "pydantic>=2.5.2,<3.0.0",
    "shapely>=2.0.3,<3.0.0",
    "geopandas>=1",
    "urllib3>=2.3.0,<3.0.0",
    "validators>=0.34.0,<1.0.0",
    "numpy>=2.2.3,<3.0.0",
    "pystac-client>=0.8.6,<0.9.0",
    "pyarrow>=19.0.1,<20.0.0",
    "contextily>=1.6.2,<2.0.0",
    "dask[distributed]>=2023.1.1",
    "planetary-computer>=1.0.0,<2.0.0",
    "stackstac[viz]>=0.5.1,<0.6.0",
    "rioxarray>=0.19.0",
    "scikit-image>=0.24.0",
]

[project.urls]
Repository = "https://github.com.mcas.ms/jap546/eo-basic-example"

[project.scripts]
download = "main:download_missing_files"
setup = "download.setup.commands:create_project_directories"

[project.optional-dependencies]
dev = [
    "pre-commit>=2.20.0",
    "ruff>=0.11.5",
    "nox>=2025.2.9",
    "mypy>=1.11.0,<2.0.0",
    "pandas-stubs>=2.2.2.240603,<3.0.0.0",
    "typing-extensions>=4.5.0,<5.0.0",
    "types-python-slugify>=8.0.0.2,<9.0.0.0",
    "types-requests>=2.28.11.13,<3.0.0.0",
    "pytest>=7.2.1,<8.0.0",
    "pytest-cov>=4.0.0,<5.0.0",
    "pytest-mock>=3.10.0,<4.0.0",
    "coverage>=6.3.2,<7.0.0",
]

[tool.hatch.build.targets.wheel]
packages = ["download"]
exclude = [
    ".github",
    ".flake8",
    ".pylintrc",
    "mypy.ini",
    ".coveragerc",
    "Makefile",
    "scripts",
    "tests",
]

[tool.mypy]
config_file = ".github/linters/.mypy.ini"

[tool.ruff]
target-version = "py312"
line-length = 100
fix = true
exclude = [".ipynb"]

[tool.ruff.lint]
select = [
    # flake8-2020
    "YTT",
    # flake8-bandit
    "S",
    # flake8-bugbear
    "B",
    # flake8-builtins
    "A",
    # flake8-comprehensions
    "C4",
    # flake8-debugger
    "T10",
    # flake8-simplify
    "SIM",
    # isort
    "I",
    # mccabe
    "C90",
    # pycodestyle
    "E",
    "W",
    # pyflakes
    "F",
    # pygrep-hooks
    "PGH",
    # pyupgrade
    "UP",
    # ruff
    "RUF",
    # tryceratops
    "TRY",
]
ignore = [
    # DoNotAssignLambda
    "E731",
    "PLR0913",
]
exclude = ["gunicorn_conf.py", "tests/", "scripts/", "*.ipynb"]

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["S101"]

[tool.ruff.format]
preview = true
exclude = ["*.ipynb"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.isort]
known-first-party = ["download"]

[tool.pytest.ini_options]
pythonpath = ["download"]
addopts = "--cov=download"
testpaths = ["tests/download"]
filterwarnings = "ignore::pytest.PytestDeprecationWarning"

[tool.coverage.paths]
source = ["download"]

[tool.coverage.run]
branch = true
source = ["download"]

[tool.coverage.report]
show_missing = true
exclude_also = [
    "def __repr__",
    "if self.debug:",
    "if settings.DEBUG",
    "raise AssertionError",
    "raise NotImplementedError",
    "if 0:",
    "if __name__ == .__main__.:",
    "if TYPE_CHECKING:",
    "class .*\\bProtocol\\):",
    "@(abc\\.)?abstractmethod",
]
